// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbhavqnskaegqkejyngl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiaGF2cW5za2FlZ3FrZWp5bmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDIyMzcsImV4cCI6MjA2MTY3ODIzN30.M-nsN-YegDt7ciUF1QFo2xAzsGL1NMmzktSIkmnry1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);